WIP Passage au WGS 84 🌐
fab-geocommuns/RNB-coeur pull request #265
Opened 2023-11-15 11:32 UTC by fchabouis

Groooosse PR qui convertit tous nos champs en Lambert en WGS84, afin de nous permettre de gérer les territoires français non couverts par le Lambert 93.

La contrepartie est que toutes les opérations liées à des distances sont un peu plus compliquées à faire qu'en Lambert, d'où l'adaptation à plusieurs endroits du SQL.

2023-11-16 11:08 UTC, pauletienney commented
On doit vérifier si la fonction prepare_point dans BuildingGuessParam fonctionne toujours d'un point de vue logique.
Elle vérifie que la distance entre deux points est inférieur à 1000m. Maintenant qu'on est en WGS84/degrés, il est possible qu'elle soit obsolète. Vérifier son bon fonctionnement, on attend cette même logique de d < 1000 m.

2023-11-16 11:20 UTC, pauletienney requested changes
Avant de merge, 

- [x] repasser le nom shape_wgs84 en shape
- [ ] vérifier le fonctionnement de la methode prepare_point (cf commentaire : https://github.com/fab-geocommuns/RNB-coeur/pull/265#issuecomment-1814233267)

2023-11-16 14:11 UTC, pauletienney requested changes
On a fait la conversion de la colonne shape de building en wgs84 mais qu'en est-il des données existantes pour les autres models : 

- city
- department
- plot
- address

Est-ce que la migration transforme automatiquement le contenu de la colonne ?

2023-11-16 15:49 UTC, fchabouis commented
> On a fait la conversion de la colonne shape de building en wgs84 mais qu'en est-il des données existantes pour les autres models :
> 
>     * city
> 
>     * department
> 
>     * plot
> 
>     * address
> 
> 
> Est-ce que la migration transforme automatiquement le contenu de la colonne ?

Très bien vu, je pensais que c'était le cas mais non !
J'ai fait les [changements](https://github.com/fab-geocommuns/RNB-coeur/pull/265/commits/69becdc7732775c55a629347864c0bc06607adb6) pour faire les migrations avec du code custom à la place.

2023-11-20 11:00 UTC, fchabouis commented
Finalement j'ai rajouté le package [geopy](https://geopy.readthedocs.io/en/latest/index.html?highlight=distance#module-geopy.distance), je pense qu'il pourra nous servir à l'avenir (il a des geocoders deja tout fait dedans par exemple) et il permet de calculer des distances en metre entre des points en WGS 84, ce qui est compliqué de faire avec GEOS, le package utilisé par GeoDjango.
J'ai fait un calcul de 2 points avec la fonction distance de GeoDjango, après avoir transformé les points en utilisant un SRID métrique et mondial, j'ai eu 40m d'écart pour 2 points séparés de 100m, ça m'a semblé beaucoup...
Ici on a un calcul correct qui est fait assez facilement.

2023-11-20 11:12 UTC, fchabouis commented
C'est bon de mon côté @pauletienney, merci pour la relecture. J'ai apporté les modifications discutées ensemble (calcul de la distance et renommage du champ wgs_84).

2023-11-21 09:06 UTC, merged