Ajout de l'historisation et des parents pour les buildings
fab-geocommuns/RNB-coeur pull request #270
Opened 2023-11-22 14:07 UTC by fchabouis

L'[extension](https://github.com/arkhipov/temporal_tables) initialement testée est une extension écrite en C et n'est pas disponible dans Scaleway (et n'est pas installable non plus).
Par chance, un [autre projet](https://github.com/nearform/temporal_tables) a entrepris une réécriture en pur SQL et il est possible d'installer l'extension en exécutant des commandes SQL dans la base.

Cette PR ajoute une migration manuelle qui installe l'extension, créé la table d'historisation, active les triggers, ajoute un champ `tstzrange` à la table batid_buildings.

J'en profite également pour ajouter un champ `parent_buildings`qui permettra de stocker la liste des buildings parents, ce qui sera utile quand on voudra tracer la filiation des éléments de cette table (en cas de merge de bâtiments par exemple). C'est plus facile de l'ajouter avant la création de la table d'historisation, pour qu'elle soit inclue dedans.

2023-11-23 16:08 UTC, fchabouis commented
rappel pour moi-même : faire attention lors du merge, #266 rajoute un champ dans la table Building et il faut le rajouter dans la création de la table d'history, au bon endroit.

2023-11-28 09:14 UTC, pauletienney requested changes
Franchement c'est top. J'ai suggéré qq minis modifications dans models (rien de structurant)

2023-11-28 09:21 UTC, fchabouis commented on app/batid/models.py
> +    parent_buildings = models.JSONField(null=True)
Je ne sais pas si tu te souviens des tests que j'avais fait à la Toussain et que je vous avais présenté ? Avec les requêtes SQL récursives, il est possible de facilement trouver tous les descendants d'un building si on les stocke sous forme de liste dans un jsonb.

C'est peut être un peu trop anticipé, mais je me dis qu'au pire si ça va pas, on pourra modifier le champ.

2023-11-28 09:28 UTC, fchabouis commented on app/batid/models.py
> +    sys_period = DateTimeRangeField(null=False, default=from_now_to_infinity)
ok https://github.com/fab-geocommuns/RNB-coeur/pull/270/commits/09193831a6c759a283fdf163d2c5fe8e8fb71f22

2023-11-28 09:36 UTC, fchabouis commented
> rappel pour moi-même : faire attention lors du merge, #266 rajoute un champ dans la table Building et il faut le rajouter dans la création de la table d'history, au bon endroit.

fait avec https://github.com/fab-geocommuns/RNB-coeur/pull/270/commits/ecbf41383f84f1967250b944010ad5e0907f3298

2023-11-28 12:57 UTC, pauletienney approved these changes

2023-11-28 13:26 UTC, merged