Nouvelle version du système de guess
fab-geocommuns/RNB-coeur pull request #328
Opened 2024-03-05 16:53 UTC by pauletienney

On a constaté que les points fournis par les bases de données externes étaient globalement de bonnes qualité. 
Partant de ce constat, nous avons créé un outil permettant de [trouver le bâtiments correspondants à un point](https://github.com/fab-geocommuns/RNB-coeur/pull/314).

Cette PR construit sur cette approche et créé un nouvel outil de rapprochement voué à remplacer le système actuel basé sur un calcul de score.

L'approche de ce nouveau rapprochement est une succession d'étapes de la plus sûre et plus précise (trouver un bâtiment à partir d'un point) jusqu'aux plus gourmandes. La notion de score est écartée, celui-ci introduisant plus de complexité que de bénéfice.

Les étapes du rapprochement sont dans l'ordre : 

1. Vérification si un bâtiment tombe sur le point donné
2. Vérification si le point est suffisamment proche d'un bâtiment et suffisamment loin des autres bâtiments
3. Géocodage de l'adresse grâce à l'[API de la BAN](https://api.gouv.fr/les-api/base-adresse-nationale) et identification d'un bâtiment RNB grâce à l'identifiant BAN récupéré
4. Géocodage du nom du bâtiment grâce à l'[API Photon fournie par Komoot](https://photon.komoot.io/)

Quelques points à noter :
- La class `Guesser` n'est pas encore accessible via un endpoint. C'est toujours le système de score qui est installé sur `/api/alpha/buildings/guess`
- Nous pourrions drastiquement gagner en vitesse en hébergeant nos propre instance d'[AddOk](https://github.com/addok/addok) et [Photon](https://github.com/komoot/photon)
- Il est probable qu'on puisse faire monter la performance du géocodage du nom du bâtiment si nous installions et configurions notre propre instance Photon

2024-03-11 14:29 UTC, pauletienney commented on app/batid/services/geocoders.py
Les geocoders renvoient maintenant des Response plutôt que la donnée directement. Cela permet de vérifier si on a bien reçu un status_code 200.

2024-03-12 14:15 UTC, fchabouis requested changes
Beau travail ! J'ai fait quelques commentaires, notamment dans les tests.

2024-03-12 14:15 UTC, fchabouis commented on app/batid/tests/test_guess.py
> +    def test_ambiguous_point(self):
Tous les tests passent dans le setup et créent un fichier workfile via `_create_guess_work_file`, et il faut à priori supprimer ce fichier après chaque execution de test.

Je crois que tu peux le faire dans une fonction tearDown() :
```python
    def tearDown(self):
      if os.path.exists(self.WORK_FILE):
        os.remove(self.WORK_FILE)
```

2024-03-12 14:15 UTC, fchabouis commented on app/batid/tests/test_guess.py
> +class TestGuesser(TransactionTestCase):
Les tests sont assez lent (13sec pour 7 tests sur ma machine), à cause des nombreux `sleep`.
Cela serait bien de pouvoir définir le temps de sleep à la création du guesser, de mettre 0,8 seconde par défaut, mais de pouvoir mettre 0 quand on fait tourner les tests.

2024-03-12 14:27 UTC, pauletienney commented on app/batid/services/guess_bdg_new.py
> +    def guess_batch(cls, guesses: dict) -> dict:
Je suis en train de préparer cela sur une autre branche.

2024-03-12 14:39 UTC, pauletienney commented on app/batid/tests/test_guess.py
> +        self.assertIsNone(reason)
- Guesser par encore passé par une étape = `finished_steps` ne contient pas l'étape concernée
- Guesser passé par cette étape mais sans résultat probant = `finished_steps` contient l'étape concernée, `match_reason` est différent de celles correspondant à cette étape

2024-03-12 14:42 UTC, pauletienney commented on app/batid/tests/test_guess.py
> +class TestGuesser(TransactionTestCase):
Oui bonne idée. Je peux intégrer ça la nouvelle branche que je fais pour rendre modulaire le guesser

2024-03-12 15:29 UTC, fchabouis approved these changes
👍

2024-03-12 16:10 UTC, merged