WIP Tremble, bosquet
fab-geocommuns/RNB-coeur pull request #349
Opened 2024-03-19 16:13 UTC by fchabouis

Le minimum syndical pour faire disparaitre un building de la base depuis la table des contributions dans l'admin.

reste à faire : 
- ajouter un champ texte pour justifier l'action.
- ajouter des tests

suite de #348

2024-03-25 10:38 UTC, pauletienney requested changes
Je vois la PR comment la version embryonnaire des premières contributions. Les outils backoffice fabriqués ont certainement vocation à vivre sur le front assez rapidement.

Il y a un point qui me gêne un peu : on adapte la génération des tuiles pour qu'elles n'affichent plus les bâtiments où `is_active = False`mais lorsque qu'on distribue les bâtiments sur d'autres canaux (par exemple en listant les bâtiments d'une ville via /api/alpha/buildings?insee_code=12345) on continue de distribuer les bâtiments irréels. A mon avis on devrait faire en sorte qu'au moins le endpoint de listing de bâtiments ne présente plus le bosquet. Qu'en penses-tu @fchabouis ?

2024-03-25 10:38 UTC, pauletienney commented on app/batid/tests/test_views.py
> +        self.assertEqual(response.status_code, 403)
```suggestion
        # we expect a 403: for the moment only superuser can contribute
        self.assertEqual(response.status_code, 403)
```

2024-03-25 10:38 UTC, pauletienney commented on app/batid/views.py
> +            contribution = Contribution.objects.get(id=contribution_id)
Un appel `.get()` ne retournant pas de résultat fait crasher django.
On peut faire : 
```suggestion
            try:
                contribution = Contribution.objects.get(id=contribution_id)
            except Contribution.DoesNotExist:
                # Return a 404 ?
                raise HttpResponseNotFound(f"We could not find find contribution {contribution_id}")
```

2024-03-25 11:28 UTC, fchabouis commented on app/batid/views.py
> +            contribution = Contribution.objects.get(id=contribution_id)
je découvre l'existence de cette fonction très pratique https://docs.djangoproject.com/fr/5.0/topics/http/shortcuts/#get-object-or-404

2024-04-02 09:27 UTC, pauletienney approved these changes
Go

2024-04-02 09:27 UTC, merged