Rapprochement des pans de toit de Lyon - échantillon
fab-geocommuns/RNB-coeur pull request #357
Opened 2024-03-28 13:13 UTC by pauletienney

La métropole du Grand Lyon nous a fourni un échantillon (9k+ lignes) de leur [jeu de données des pans de toit](https://data.grandlyon.com/portail/fr/jeux-de-donnees/volumes-toiture-3d-2018-bati-metropole-lyon/info) de la métropole.

Cette PR consiste à créer une nouvelle logique de rapprochement dédiés à ces pans de toit.

2024-03-28 13:20 UTC, pauletienney commented on app/batid/services/guess_bdg_new.py
> +    def display_reason(
Méthode permettant d'afficher un échantillon aléatoire des guess ayant trouvé une correspondance pour une raison X

2024-03-29 10:28 UTC, fchabouis requested changes
Nice !
J'ai fait quelques commentaires.
Par ailleurs est-ce que tu supprimes expres le csv de data-es ?

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +    def display_reason(
Peut-être pourrions nous l'appeler `def matches_sample(match_reason, sample_size, sample_columns)` pour être plus explicite sur son utilité ?

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +                # "match": None,
ligne à supprimer ?

```suggestion
```

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +        closest_bdgs = get_closest_from_poly(roof_poly, 35)[:20]
J'ai l'impression que c'est une typo

```suggestion
        closest_bdgs = get_closest_from_poly(roof_poly, 35)[:2]
```

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +        # Est-ce qu'il yn seul bâtiment qui intersects et le second bâtiment le plus proche est assez loin ?
```suggestion
        # Est-ce qu'il y a un seul bâtiment qui intersecte et le second bâtiment le plus proche est assez loin ?
```

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +    def _closest_bdg_contains_roof(
j'ai l'impression que cette fonction n'est pas utilisée.

2024-03-29 10:28 UTC, fchabouis commented on app/batid/services/guess_bdg_new.py
> +        # Est-ce qu'il y a un seul batiment qui couvre à plus de X% le pan de toit ?
J'aimerais bien qu'on choisisse une langue pour les commentaires :)

2024-03-29 10:28 UTC, fchabouis commented on docker-compose.yml
> +      - "8890:8888"
Erreur ?

```suggestion
```

2024-05-17 15:29 UTC, pauletienney commented on app/batid/services/guess_bdg_new.py
> +        closest_bdgs = get_closest_from_poly(roof_poly, 35)[:20]
Ce n'est pas une typo. On a bien besoin de récupérer plus de bâtiments (je dois avouer ne plus me souvenir pourquoi car c'est un peu lointain, je me souviens que ça a à faire avec le fait que plusieurs bâtiments peuvent avoir une distance de zéro).

2024-05-17 15:45 UTC, merged