Ajout d'une API de création de token ADS
fab-geocommuns/RNB-coeur pull request #427
Opened 2024-06-25 10:00 UTC by bbaret

Afin de créer des tokens pour les ADS, nous avons besoin d'une nouvelle API qui permet de le faire par lot.

2024-06-25 13:52 UTC, fchabouis approved these changes
J'ai pas pu tester en local car je suis bloqué sur ma branche des DPE, mais le code m'a l'air bon. Tu as pu tester que ça marchait sur ton poste ?
Bravo pour la PR :)

2024-06-25 15:30 UTC, pauletienney requested changes

2024-06-25 15:30 UTC, pauletienney commented on app/api_alpha/urls.py
> +    path("api-auth/", obtain_auth_token),
@bbaret Je ne suis pas sûr de comprendre à quoi sert cette ligne. J'ai l'impression qu'on pourrait se passer de cette URL.

2024-06-25 15:30 UTC, pauletienney commented on app/api_alpha/tests/test_ads.py
> +
je pense qu'en plus de tester la réponse renvoyée par la requête, on devrait vérifier que les éléments ont bien été créé en base. J'aurais même tendance à pousser en vérifiant que le user concerné peut bien créer une ADS.

2024-06-25 15:34 UTC, bbaret commented on app/api_alpha/urls.py
> +    path("api-auth/", obtain_auth_token),
Cette URL sert à récupérer un token via un compte superuser afin d'utiliser l'autre API. As-tu une autre façon de faire ?

2024-06-26 09:06 UTC, fchabouis commented
Suite à discussion au tél, on s'est dit que ce serait bien que les utilisateurs créés ne puissent modifier que les modèles liés aux ADS et pas les autres, et de rajouter quelques tests pour vérifier que cette restriction de permission marche bien.
Ca peut être fait dans une PR à part.

2024-06-26 09:19 UTC, bbaret commented on app/api_alpha/urls.py
> +    path("api-auth/", obtain_auth_token),
Suite à un point avec Francis, j'avais une incompréhension de ce token: je pensais qu'il était décoléré du token d'authentification de Django. Je supprime la route.

2024-06-26 13:50 UTC, fchabouis approved these changes
Top

2024-06-27 09:40 UTC, merged