Contribution CartOlympiques : récupérer le nombre de contributions et le classement
fab-geocommuns/RNB-coeur pull request #430
Opened 2024-06-26 13:12 UTC by fchabouis

Via un paramètre optionnel dans la requête qui permet de créer la contribution, on récupère les infos qui nous intéressent dans la réponse 201 du serveur.

2024-06-26 13:32 UTC, bbaret commented on app/api_alpha/views.py
> +    select email, count(*) as count, rank() over(order by count(*) desc) from batid_contribution where email is not null group by email order by count desc;
```
    with ranking as (
      select email, count(*) as count, rank() over(order by count(*) desc)
      from batid_contribution
      where email is not null and email != ''
      group by email order by count desc
    )
  select * from ranking where email = '%s'
```

Je propose de retourner directement la donnée intéressante pour éviter de récupérer tout le classement depuis la DB.
J'ai aussi rajouté le prédicat `email != ''` pour ne pas inclure les emails vides.

2024-06-26 15:45 UTC, fchabouis commented on app/api_alpha/views.py
> +    select email, count(*) as count, rank() over(order by count(*) desc) from batid_contribution where email is not null group by email order by count desc;
une bien bonne idée !
https://github.com/fab-geocommuns/RNB-coeur/pull/430/commits/dff18f926c57372f60cfa5be34cd1b605b142f8b

2024-06-27 08:52 UTC, pauletienney requested changes
Mini remarques + ajout d'une valeurs aux stats globales.

2024-06-27 08:52 UTC, pauletienney commented on app/api_alpha/views.py
> +            if request.query_params.get("classement") == "true" and request.data.get(
On peut rester en anglais
```suggestion
            if request.query_params.get("ranking") == "true" and request.data.get(
```

2024-06-27 08:52 UTC, pauletienney commented on app/api_alpha/views.py
> +    def classement(self, request, *args, **kwargs):
Idem. Restons en anglais non ?
```suggestion
    def ranking(self, request, *args, **kwargs):
```

2024-06-27 08:52 UTC, pauletienney commented on app/api_alpha/views.py
> +        data = {"individual": individual, "departement": departement}
Peut-on ajouter une troisième valeur `global` qui serait un count des contributions dont le statut n'est pas refusé ? Ce sera pour faire la barre globale de remplissage jusqu'à 1000.

2024-06-27 12:22 UTC, fchabouis commented on app/api_alpha/views.py
> +            if request.query_params.get("classement") == "true" and request.data.get(
ok

2024-06-27 12:22 UTC, fchabouis commented on app/api_alpha/views.py
> +    def classement(self, request, *args, **kwargs):
ok

2024-06-27 12:36 UTC, fchabouis commented on app/api_alpha/views.py
> +        data = {"individual": individual, "departement": departement}
c'est fait https://github.com/fab-geocommuns/RNB-coeur/pull/430/commits/7528f3a2d03fd00e7abaa80a4dcbfca4a0b676a9

2024-06-28 12:17 UTC, pauletienney approved these changes

2024-06-28 12:17 UTC, merged