Evaluation des BALs
fab-geocommuns/RNB-coeur pull request #470
Opened 2024-10-01 08:31 UTC by pauletienney

J'ai créé un notebook pour évaluer dans quelle mesure l'exploitation des BALs pourrait : 

- [nous aider à la création de nouveaux liens bâtiment <> adresses](https://www.notion.so/referentielnationaldesbatiments/BAL-Am-liorer-lien-bati-adresse-3aab55daea4f418bbe9b65c79dcdf9c4?pvs=4)
- [nous aider à la création de nouveaux bâtiments](https://www.notion.so/referentielnationaldesbatiments/Etudier-si-les-BAL-aident-trouver-de-nouveaux-b-timents-10d43ec9d11e80f9a58ef32b7a4e370f?pvs=4)

Les résultats sont prometteurs en particuliers pour l'enrichissement du lien bati <-> adresse

2025-02-26 14:57 UTC, leonkenneth requested changes

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +                # pprint(plots)
A enlever pour la version finale

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +            AND st_intersects(p.shape, b.shape)
J'imagine que le pattern `shape && something AND st_intersects(shape, something)` c'est une genre d'optimisation courante c'est ça ?

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +        """
Donc, ça ça nous donne :
- les ID-RNB et leurs shape et adresses actuelles
- les cadastres qui intersectent les adresses candidates
- les ID-RNB qui intersectent ces cadastres et à quel point

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +                cursor.execute(q, params)
Au final `q` est utile que ici ? Je me dis que ce serait pas mal de split chaque méthode de l'algo en fonction pour encapsuler les morceaux de logique et avoir une méthode high-level moins touffue

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +                            new_ban_id.add(link)
Donc ça c'est un cas où finalement l'adresse n'a pas vraiment changé mais on a une instabilité de l'ID BAN ?

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +            st_area(st_intersection(b.shape, p.shape)) / st_area(b.shape) AS bdg_cover_ratio,
Ca me fait penser : vu qu'on envoie cette donnée via l'API et qu'on nous demande de l'exporter, peut-être qu'on pourra créer une vue des recouvrement batiments / cadastre.

Auquel cas ça simplifierait peut-être aussi ce genre de de requêtes (on pourrait directement JOIN sur un taux de recouvrement suffisant)

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +                    already_exists = _address_already_exists(bdg, row)
Au final c'est la même logique une fois le lien `(building, possible_addresse)` collecté, peut-être à extraire ?

2025-02-26 14:57 UTC, leonkenneth commented on app/batid/tests/test_import_bal.py
> +    def test_create_link_building_address_in_buffer(self):
Est-ce que ça teste la partie "in plot buffer" ou est-ce que ça teste l'intersection avec la shape du batiment ?

2025-02-27 09:19 UTC, leonkenneth commented on app/batid/services/imports/import_bal.py
> +            st_area(st_intersection(b.shape, p.shape)) / st_area(b.shape) AS bdg_cover_ratio,
Oui effectivement je pensais à une vue matérialisée, dans le cas où de toutes façons on devrait la calculer pour l'export et qu'elle pourrait être utile si c'est un lien beaucoup utilisé.

Par contre je n'ai effectivement pas en tête la cardinalité des batiments / plots, ça peut faire beaucoup pour peu de gain.

Anyway pas pour cette PR

2025-02-27 10:01 UTC, leonkenneth commented on app/batid/tests/test_import_bal.py
> +    def test_create_link_building_address_in_buffer(self):
J'avais l'impression dans le code qu'il fallait un `batid_plot` pour le calcul de l'overlap, mais je ne le vois pas explicitement dans les tests contrairement à l'adresse et le batiment. Il y a un mock ou des fixtures de test quelque part ?

2025-02-27 10:54 UTC, pauletienney commented on app/app/settings.py
> +            minute=0, hour=0, day_of_month=20, month_of_year="1,4,7,10"
On peut sans doute augmenter nettement la fréquence. De mémoire les BAL sont publiées chaque semaine.

2025-02-27 10:57 UTC, pauletienney commented on app/batid/services/imports/import_bal.py
> +    # FIXME should we create a building_import_history ?
Je pense qu'on doit pouvoir auditer d'où vient la modification d'un bâtiment. De mémoire, les possibilités sont : 
- d'un import (c'est le cas de la bd topo et de la bdnb)
- d'un datafix (cf le nettoyage qui a été fait en fin d'année dernière avec les bâtiment légers)
- de contributions

L'utilisation des BAL me semble relever de la même approche que l'import de la BD Topo et de la BDNB.

2025-02-27 13:52 UTC, pauletienney commented on app/batid/tasks.py
> +    convert_bal_impl(src_params, bulk_launch_uuid)
Dans les import de BD Topo et du cadastre, j'ai souvent importé les fonctions qui éxecutent le boulot en leur donnant un alias (voir dans la partie `import` en haut du fichier). J'ai suffixé les fonctions avec `_job`. Je suggère qu'on garde cette façon de faire pour uniformiser.

2025-02-27 14:01 UTC, pauletienney commented on app/batid/tasks.py
> +    dpts = dpts_list(dpt_start, dpt_end)
Je vois sur https://adresse.data.gouv.fr/data/ban/adresses/latest/csv-bal que la BAL propose le téléchargement pour les territoires 984, 988 et 989. C'est trois territoires ne sont pas inclus dans `dpts_list` (via `com_list`). Est-ce que ce serait l'occasion de les intégrer ?

2025-02-27 14:11 UTC, pauletienney commented on app/batid/services/imports/import_bal.py
> +
J'ai l'impression qu'on pourrait simplifier la structure des tâches. On pourrait avoir trois tâches : 
- une de téléchargement
- une dédiée à l'ajout en base des adresse qu'on ne connait pas
- une dédiée à la création de nouveaux liens bâtiment <> adresse

Il me semble que de cette façon, on aurait pas à passer par un CSV intermédiaire et ça découplerait `convert_bal` et `import_bal_addresses` qui me semblent très imbriquées

2025-02-27 14:25 UTC, fchabouis commented on app/batid/services/imports/import_bal.py
> +                Building.objects.bulk_update(buildings_to_update, ["addresses_id"])
⚠️ Il est très important de ne jamais "toucher" un bâtiment à la main dans le RNB et de toujours passer par les fonctions qui sont définies dans `models.py`.

Pour mettre un jour un bâtiment, il faut passer par `Building.update()`définie [ici](https://github.com/fab-geocommuns/RNB-coeur/blob/dfacc2dbcf06aa2fa89062ef30675efeddf80de6/app/batid/models.py#L192).

Cette fonction nous garantit que le changement sera effectué en garantissant sa tracabilité (event_origin, event_user) ainsi que la cohérence du référentiel (on ne peut pas mettre à jour un bâtiment inactif, etc). D'autres règles vont probablement être rajoutées par la suite (par exemple, si deux adresses sont associées à un bâtiment, vérifier que les deux adresses ne sont pas distantes de plus de X km) et elles seront probablement branchées dans ces méthodes là. Et donc il ne faut jamais les bypasser. 

Paul avait même parlé de désactiver les fonctions natives pour empêcher leur utilisation mais elle sont souvent utiles dans les tests pour créer des test case custom facilement, notamment de situation qui ne sont pas sensées arriver. Par exemple [ici](https://github.com/fab-geocommuns/RNB-coeur/pull/546/commits/eb2669fb3974977e8ba360ff8c4e6c1a5da3ceda).

2025-02-27 14:29 UTC, fchabouis commented on app/batid/services/imports/import_bal.py
> +                cursor.execute(q, params)
oui je suis d'accord que cette grosse fonction gagnerait à être découpée :)

2025-02-27 14:29 UTC, pauletienney commented on app/batid/services/imports/import_bal.py
> +def _create_link_building_address(certified_df):
Même constat que Leo mais avec la proposition de découper cette fonction. Je trouve qu'elle fait baucoup de chose (fait de la création de liens batiment adresse en batch en suivant deux méthodes et vérifie si il y a des adresses à créer, créé des stats). Elle mérite d'être découpée pour faciliter sa lecture et sa maintenance.

2025-02-27 14:32 UTC, pauletienney commented on app/batid/services/imports/import_bal.py
> +                Building.objects.bulk_update(buildings_to_update, ["addresses_id"])
Effectivement, on a maintenant une sorte de logique métier de mise à jour qu'on doit respecter partout.

2025-03-18 16:17 UTC, fchabouis commented
remplacé par https://github.com/fab-geocommuns/RNB-coeur/pull/565 => cloture

2025-03-18 16:20 UTC, fchabouis commented
remplacé par https://github.com/fab-geocommuns/RNB-coeur/pull/565 => cloture

2025-03-18 16:20 UTC, closed without merging