Fichier de diff enrichi : filiation, evenements et is_active
fab-geocommuns/RNB-coeur pull request #503
Opened 2024-11-19 15:30 UTC by pauletienney

Suite au feedback du CSTB on ajoute des champs au fichier de diff pour que l'on puisse mieux suivre les modifications faites aux bâtiments. On ajoute les colonnes : 

- is_active
- parent_buildings
- event_type
- event_id

Aussi, dans la colonne `action`, j'ai changé la valeur `delete` en `deactivate

2024-11-21 09:08 UTC, fchabouis commented on app/api_alpha/views.py
> +                            WHEN event_type = 'deactivation' THEN 'deactivate'
```suggestion
                            WHEN event_type = 'deactivation' THEN 'deactivate'
```

Il n'y aura plus de `delete` dès ce soir si tout va bien

2024-11-21 09:12 UTC, fchabouis commented on app/api_alpha/tests/test_views.py
>      def test_diff_create_update_delete(self):
```suggestion
    def test_diff_create_update_deactivate(self):
```

2024-11-21 09:18 UTC, fchabouis commented on app/api_alpha/tests/test_views.py
> +        # todo : use the future split() method when it will be implemented
ça pourrait être l'occasion de le faire 😇

2024-11-21 09:21 UTC, fchabouis requested changes
Dans l'ensemble ça me va bien, j'ai laissé quelques suggestions.

2024-11-26 09:23 UTC, pauletienney commented on app/api_alpha/views.py
> +                            WHEN event_type = 'deactivation' THEN 'deactivate'
Je viens de vérifier et on a encore des `delete` en base. Je supprime la ligne en doublon mais je conserve celle prenant en compte `delete`

2024-11-26 09:29 UTC, pauletienney commented on app/api_alpha/tests/test_views.py
> +        # todo : use the future split() method when it will be implemented
Je ne suis pas sûr que les splits soient pour tout de suite, je pense qu'on peut repousser un peu la création de la fonction.

2024-11-26 09:30 UTC, pauletienney commented
J'ai deux petites retouches suite à tes commentaires @fchabouis . Je veux bien un relecture quand tu peux stp.

2024-11-27 08:22 UTC, bbaret approved these changes

2024-11-27 10:15 UTC, fchabouis approved these changes

2024-11-29 13:01 UTC, merged