Tâche pour passer les delete à deactivate
fab-geocommuns/RNB-coeur pull request #507
Opened 2024-11-26 16:46 UTC by pauletienney

La [PR502](https://github.com/fab-geocommuns/RNB-coeur/pull/502) utilise le terme `deactivate` au lieu de `delete` ou `deletion` là où c'était utilisé.

Le problème est qu'en lançant la requête décrite dans la 502, on a constaté que celle-ci durait bien trop longtemps et n'a finalement pas abouti.

Un comptage du nombre de bâtiments ayant `event_type='delete'` en base indique qu'il y en a encore plus de quatre millions.

Cette PR créé une tâche qui met à jour les bâtiments concernés 10.000 par 10.000. On fait particulièrement attention à ce que la trigger d'historisation soit désactivée pendant chaque mise à jour.

Comme lors de la 502, je ferai un snapshot de la base avant de lancer cette tâche.

2024-11-27 08:20 UTC, bbaret approved these changes

2024-11-27 09:46 UTC, fchabouis commented
Il y a un petit piège de sémantique dans cette histoire, c'est que j'ai mis dans `event_type` des noms (creation, deactivation, merge,...) mais que certains de ces noms sont aussi des verbes, comme `merge`, `split`. Et je m'étais moi même embrouillé en mettant des event_type `delete` au lieu de `deletion`. Donc là on veut mettre `deactivation` et j'aimerais bien que le mot `deactivate` n'apparaisse jamais, parce qu'il est piegeux. D'ou ma demande, est-il possible d'appeler le job et les fonctions associées `delete_to_deactivation` plutôt que `delete_to_deactivate` ? Merci !

2024-11-27 09:47 UTC, fchabouis requested changes
Il y a un petit piège de sémantique dans cette histoire, c'est que j'ai mis dans event_type des noms (creation, deactivation, merge,...) mais que certains de ces noms sont aussi des verbes, comme merge, split. Et je m'étais moi même embrouillé en mettant des event_type delete au lieu de deletion. Donc là on veut mettre deactivation et j'aimerais bien que le mot deactivate n'apparaisse jamais, parce qu'il est piegeux. D'ou ma demande, est-il possible d'appeler le job et les fonctions associées delete_to_deactivation plutôt que delete_to_deactivate ? Merci !

2024-11-27 09:47 UTC, fchabouis commented on app/batid/services/data_fix/delete_to_deactivate.py
> +            LIMIT 1000
(ça change rien mais tu disais vouloir faire des batchs de 10 000 dans la description de la PR)

2024-11-27 10:00 UTC, fchabouis commented on app/batid/services/data_fix/delete_to_deactivate.py
> +                loop_again = cursor.rowcount > 0
j'ai modifié l'ordre de ces lignes, car `cursor.rowcount` renvoie le nombre de lignes de la dernière requête. Et si la dernière requête c'est de réactiver l'index, ça renvoie -1.

https://www.psycopg.org/docs/cursor.html#cursor.rowcount

![Capture d’écran 2024-11-27 à 10 55 52](https://github.com/user-attachments/assets/0847e5a4-2af5-4e41-a120-8083a2a5f133)

J'ai rajouté un petit [test](748eb764747aacad99736d0c732bd533c839d04d) pour vérifier que la boucle se comporte bien.

2024-11-27 10:01 UTC, fchabouis commented
Merci pour la PR :)

2024-11-28 09:05 UTC, pauletienney commented on app/batid/services/data_fix/delete_to_deactivate.py
> +                loop_again = cursor.rowcount > 0
Effectivement, j'ai été un peu vite là dessus.

2024-11-28 09:11 UTC, pauletienney commented
> Il y a un petit piège de sémantique dans cette histoire, c'est que j'ai mis dans event_type des noms (creation, deactivation, merge,...) mais que certains de ces noms sont aussi des verbes, comme merge, split. Et je m'étais moi même embrouillé en mettant des event_type delete au lieu de deletion. Donc là on veut mettre deactivation et j'aimerais bien que le mot deactivate n'apparaisse jamais, parce qu'il est piegeux. D'ou ma demande, est-il possible d'appeler le job et les fonctions associées delete_to_deactivation plutôt que delete_to_deactivate ? Merci !

C'est fait

2024-11-28 10:37 UTC, fchabouis approved these changes

2024-11-28 10:37 UTC, merged