API: recherche par adresse
fab-geocommuns/RNB-coeur pull request #516
Opened 2024-12-11 16:26 UTC by fchabouis

2024-12-12 16:43 UTC, fchabouis commented on app/api_alpha/views.py
> +    def get_paginated_response(self, data, infos):
petite pagination custom basée sur la pagination existante

2024-12-16 13:41 UTC, pauletienney reviewed
Quelques petits commentaires

2024-12-16 13:41 UTC, pauletienney commented on app/api_alpha/views.py
> +                        "description": "Liste les bâtiments du RNB associés à cette adresse. L'adresse fournie est recherchée dans la BAN afin de récupérer la clé d'interopérabilité associée. C'est v
Ca me permet de commencer la description de ce paramètre en disant que c'est une "liste de bâtiments du rnb ..." alors qu'il s'agit d'une adresse texte.


```suggestion
                        "description": "Adresse texte non structurée. L'adresse fournie est recherchée dans la BAN afin de récupérer la clé d'interopérabilité associée. C'est via cette clé que sont filtrés les bâtiments. Si le geocodage échoue aucun résultat n'est renvoyé et le champ <code>status</code> de la réponse contient <code>geocoding_no_result</code>",
```

2024-12-16 13:41 UTC, pauletienney commented on app/api_alpha/views.py
> +                        "required": False,
Si la valeur n'est pas requise, je pense qu'il faut indiquer quelques part quelle est la valeur par défaut que nous retenons

2024-12-17 09:49 UTC, fchabouis commented on app/api_alpha/views.py
> +                        "description": "Liste les bâtiments du RNB associés à cette adresse. L'adresse fournie est recherchée dans la BAN afin de récupérer la clé d'interopérabilité associée. C'est v
Tu mets les balises <code> pour une raison particulière ? Je vois qu'ils n'apparaissent pas dans la doc sur le gitbook, ils sont supprimés quelque part en route on dirait.

2024-12-17 09:53 UTC, fchabouis commented on app/api_alpha/views.py
> +                        "description": "Liste les bâtiments du RNB associés à cette adresse. L'adresse fournie est recherchée dans la BAN afin de récupérer la clé d'interopérabilité associée. C'est v
Le changement de la première phrase est pertinent 👍

2024-12-31 08:43 UTC, pauletienney requested changes
Ca semble nickel. Selon moi, il manque juste la prise en compte d'une indispo du serveur BAN.

2024-12-31 08:43 UTC, pauletienney commented on app/api_alpha/tests/test_buildings.py
> +
On devrait tester le cas où le geocoder BAN n'est pas disponible. Par exemple, que se passe-t-il si le serveur BAN nous répond avec une erreur 500 ou un timeout (408) ?

2025-01-07 10:58 UTC, fchabouis commented on app/api_alpha/tests/test_buildings.py
> +
je rajoute ça : si l'API BAN renvoie autre chose qu'une 200, je renvoie une [erreur 503](https://http.cat/503) qui convient bien pour une service momentanément indisponible. On verra si on a besoin de plus de finesse que cela par la suite dans les status qu'on renvoie.

2025-01-07 14:11 UTC, bbaret approved these changes

2025-01-07 14:24 UTC, merged