API : recherche de bâtiment par parcelle cadastrale
fab-geocommuns/RNB-coeur pull request #519
Opened 2024-12-18 11:16 UTC by fchabouis

Ajout d'un endpoint qui permet de lister des bâtiments qui touchent géométriquement une parcelle cadastrale.

Reste à faire : ajouter des tests

2024-12-18 15:55 UTC, fchabouis commented on app/api_alpha/views.py
> +            raise NotFound(e)
corrigé. merci copilot

2024-12-31 08:55 UTC, pauletienney requested changes
Il faudrait ajouter les tests.

2024-12-31 08:55 UTC, pauletienney commented on app/batid/exceptions.py
> +    """The given plot id is not in our database"""
Dans l'idée de faire du RNB un commun, on veut éviter de parler de "notre" base je pense.

```suggestion
    """The given plot id is not in RNB database"""
```

2024-12-31 08:55 UTC, pauletienney commented on app/batid/services/bdg_on_plot.py
> +        Building.objects.filter(is_active=True)
Je me demande si on ne devrait pas filtrer les bâtiments selon leur statut physique.
Est-ce que par défaut on veut renvoyer les bâtiments démolis ? Ca se discute.

2025-01-07 09:57 UTC, bbaret approved these changes

2025-01-07 10:29 UTC, fchabouis commented on app/batid/exceptions.py
> +    """The given plot id is not in our database"""
ok

2025-01-07 10:35 UTC, fchabouis commented on app/batid/services/bdg_on_plot.py
> +        Building.objects.filter(is_active=True)
On sera surement amené à ajouter une option pour filtrer par status par la suite. Pour le moment je colle avec le comportement par défaut du endpoint de listing des bâtiments qui liste aussi les bâtiments détruits.

2025-01-07 10:43 UTC, merged